slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:1.0.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

work_directory: &work_directory
  working_directory: ~/jul-jsonformatter

resource_class: &resource_class
  resource_class: small
  
pr_filter: &pr_filter
  filters:
    branches:
      ignore: master
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory

version: 2.1
jobs:
  changelog_updater:
    docker:
    - image: devatherock/changelog-updater:0.1.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    <<: *resource_class
    environment:
      VELA_BUILD_AUTHOR: "renovate[bot]"
      VELA_BUILD_AUTHOR_EMAIL: "29139614+renovate[bot]@users.noreply.github.com"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:86:fe:0e:c3:0e:ad:0d:1d:5c:3e:48:cf:28:39:5d"      
      - checkout
      - run: sh /scripts/entry-point.sh
      
  test:
    executor: jdk-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/jul-jsonformatter
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: |
          ./gradlew check coveralls -x test
      - store_test_results:
          path: build/test-results
  build:
    executor: jdk-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/jul-jsonformatter
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: |
          ./gradlew build publishToSonatype coveralls sonar -Dsnapshot=true -Dsonar.login=$SONAR_TOKEN -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
  publish:
    executor: jdk-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/jul-jsonformatter
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: |
          ./gradlew build publishToSonatype closeAndReleaseSonatypeStagingRepository -x check

  notify:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack -c "#33ad7f" || true          
           
workflows:
  version: 2.1
  build_test:
    jobs:
      - build:
          context:
            - docker-credentials
            - sonatype-credentials
            - sonar-credentials
            - dependencycheck-credentials
          filters:
            branches:
              only: master
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - build
  publish_artifacts:
    jobs:
      - publish:
          context:
            - docker-credentials
            - sonatype-credentials
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish
  pr_check:
    jobs:
      - changelog_updater:
          context:
            - docker-credentials
            - changelog-updater-credentials
          <<: *pr_filter
      - test:
          context:
            - docker-credentials
            - dependencycheck-credentials
          <<: *pr_filter
          requires:
            - changelog_updater