slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
       
orbs:
  gradle: circleci/gradle@2.2.0

work_directory: &work_directory
  working_directory: ~/jul-jsonformatter

resource_class: &resource_class
  resource_class: small
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory

version: 2.1
jobs:
  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#a1040c"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack
          when: on_fail
           
workflows:
  version: 2.1
  build_test:
    jobs:
      - gradle/test:
          executor: jdk-executor
          context:
            - docker-credentials
          filters:
            branches:
              ignore: 
                - master
          test_command: check coveralls -x test
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
            - bintray-credentials
            - sonar-credentials
          filters:
            branches:
              only: master
          command: build uploadArchives coveralls sonarqube -PnexusUsername=$SONATYPE_USERNAME -PnexusPassword=$SONATYPE_PASSWORD -Dsnapshot=true -Dsonar.login=$SONAR_TOKEN -x test
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - gradle/run
      - notify_failure:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - gradle/run
  publish_artifacts:
    jobs:
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
            - bintray-credentials
            - sonatype-credentials
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
          command: build uploadArchives closeAndReleaseRepository -PnexusUsername=$SONATYPE_USERNAME -PnexusPassword=$SONATYPE_PASSWORD -x test
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - gradle/run
      - notify_failure:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - gradle/run