slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.7.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
       
orbs:
  gradle: circleci/gradle@2.2.0

work_directory: &work_directory
  working_directory: ~/jul-jsonformatter

resource_class: &resource_class
  resource_class: small
  
pr_filter: &pr_filter
  filters:
    branches:
      ignore: master
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory

version: 2.1
jobs:
  changelog_updater:
    docker:
    - image: devatherock/changelog-updater:latest
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    <<: *resource_class
    environment:
      VELA_BUILD_AUTHOR_EMAIL: "bot@renovateapp.com"
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh

  notify:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack -c "#33ad7f" || true          
           
workflows:
  version: 2.1
  build_test:
    jobs:
      - gradle/run:
          name: build
          executor: jdk-executor
          context:
            - docker-credentials
            - sonatype-credentials
            - sonar-credentials
          filters:
            branches:
              only: master
          command: build publishToSonatype coveralls sonarqube -Dsnapshot=true -Dsonar.login=$SONAR_TOKEN -x test
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - build
  publish_artifacts:
    jobs:
      - gradle/run:
          name: publish
          executor: jdk-executor
          context:
            - docker-credentials
            - sonatype-credentials
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
          command: build publishToSonatype -x test
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish
  pr_check:
    jobs:
      - changelog_updater:
          context:
            - docker-credentials
            - changelog-updater-credentials
          <<: *pr_filter
      - gradle/test:
          name: test
          executor: jdk-executor
          context:
            - docker-credentials
          <<: *pr_filter
          test_command: check coveralls -x test
          requires:
            - changelog_updater